services:
  - type: web
    name: iagona-dash-temp
    env: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: API_TOKEN
      - key: DATABASE_URL
      - key: NODE_ENV
